### ISSUE TITLE
I can add your board to IceStudio IDE

### ISSUE THREAD

**Issue by benitoss** [pergola-fpga/pergola#2]
Hello I am a FPGA developer 

If you want to add your board to IceStudio you only have to send me one, and I am glad to include the board in the supported list of boards of this IDE.

IceStudio is a visual editor for open FPGA boards
https://icestudio.io/

I have already added different boards with ECP5 Lattice Model to ICEStudio
Colorlight boards --> https://github.com/FPGAwars/icestudio/pull/500
FleaFPGA-Ohm ECP5 board --> https://github.com/FPGAwars/icestudio/pull/521
and ECP-5 Evaluation Board --> https://github.com/FPGAwars/icestudio/pull/541

My email is benitoss@gmail,com if you are interested 

Rergards
Fernando

**Comment by kbeckmann** [comment]
Hi, thanks for reaching out. This project is still sort of in an unfinished state and more or less on hold. I would like to finish it properly before adding board files in external projects. I can let you know when it's ready.
